=== karimohsen/Xml/XmlTest/src/validate.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT libraries ( library+ )>
<!ELEMENT library (location,description,librarian+,book* )>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>
<!ELEMENT book ( author+,isbn,preface , part+ )>
<!ELEMENT author (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT preface (#PCDATA)>
<!ELEMENT part (chapter+)>
<!ELEMENT chapter ( summary+ , sections+ )>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT sections (paragragh+)>
<!ELEMENT paragragh (#PCDATA)>
<!ATTLIST library name CDATA #REQUIRED>
<!ATTLIST book title CDATA #REQUIRED
author CDATA "Unknown"
isbn CDATA #FIXED "10"
>
<!ATTLIST part name CDATA #IMPLIED
title CDATA #REQUIRED
>
<!ATTLIST part title CDATA #REQUIRED
>
<!ATTLIST chapter title CDATA #REQUIRED
>

=== karimohsen/Xml/XmlTest/src/xmlTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libraries SYSTEM "validate.dtd">
<libraries>
    <library name="library1"  >
        <location>
             <![CDATA[
                ]]>
        </location>
        <description>
            <![CDATA[
                ]]>
        </description>
        <librarian>
        </librarian>
        <book title="xyz"   >
            <author>
            </author>
            <isbn>
            </isbn>
            <preface>
                <![CDATA[
                ]]>
            </preface>
            <part title="part1" >
                <chapter title="chapter1" >
                    <summary>
                    <![CDATA[
                        ]]>
                    </summary>
                    <sections>
                        <paragragh>
                            <![CDATA[
                                ]]>
                        </paragragh>
                    </sections>
                </chapter>
            </part>
        </book>
    </library>
</libraries>
